### ISSUE TITLE
Unable to generate clutrr data

### ISSUE THREAD

**Issue by aadityanaik** [facebookresearch/clutrr#23]
I am trying to generate clutrr data using the command given in the README:
```bash
python main.py --train_tasks 1.2 --test_tasks 1.2 --train_rows 500 --test_rows 10 --equal --holdout --use_mturk_template --data_name "Robust Reasoning - clean - AMT" --unique_test_pattern
```

However, I encounter this error:
```
2024-09-20 03:41:00,047 - INFO - Data generation started for configurations :
2024-09-20 03:41:00,047 - INFO -
togrep : ['--train_tasks', '1.2', '--test_tasks', '1.2', '--train_rows', '500', '--test_rows', '10', '--equal', '--holdout', '--use_mturk_template', '--data_name', 'Robust Reasoning - clean - AMT', '--unique_test_pattern']

Downloading placeholder data
sha256 : 58ad947162d2293c2259264e3913235e1c3b73e807a8db0fcd867eb09c972187
checking ...
Traceback (most recent call last):
  File "/home/aadityanaik/clutrr/clutrr/main.py", line 383, in <module>
    cl = Clutrr(args)
         ^^^^^^^^^^^^
  File "/home/aadityanaik/clutrr/clutrr/main.py", line 62, in __init__
    self.setup()
  File "/home/aadityanaik/clutrr/clutrr/main.py", line 370, in setup
    raise AssertionError("downloaded corrupt data, sha256 doesn't match")
AssertionError: downloaded corrupt data, sha256 doesn't match
```

This seems to stem from trying to download the `cleaned_placeholders.zip` file, and the download link for that doesn't seem to be working. Is there any other place I can download this file from?

**Comment by xywen97** [comment]
same problem, have you solved this problem?

**Comment by MiracleLin001** [comment]
It seems author has closed the download link...

**Comment by aadityanaik** [comment]
I haven't addressed this yet

**Comment by koustuvsinha** [comment]
Hi all, apologies for the delayed response. You can try using the new generator in the develop branch: https://github.com/facebookresearch/clutrr/tree/develop . Templates are now added directly in the repo, which you can find here: https://github.com/facebookresearch/clutrr/tree/develop/clutrr/templates/amt

**Comment by MiracleLin001** [comment]
> Hi all, apologies for the delayed response. You can try using the new generator in the develop branch: https://github.com/facebookresearch/clutrr/tree/develop . Templates are now added directly in the repo, which you can find here: https://github.com/facebookresearch/clutrr/tree/develop/clutrr/templates/amt

Hi @koustuvsinha , thanks for your reply! The develop branch code works. But there are some other issue arises. When I use the `generate.sh` to generate more samples, as the program runs, the program generates graphs gradually slows down to an unacceptable speed. I wondered if there was any solution to deal with this problem. Or Is it appropriate to generate small batches of data using different seeds and concat them together?
